eport/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf.urls import include, url

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('gateway.urls', namespace="gateway") ),
    url(r'^acounts/', include('acounts.urls', namespace="acounts")),
    url(r'^applyjob/', include('applyjob.urls', namespace="applyjob")),
    url(r'^companies/', include('companies.urls', namespace="companies")),
    url(r'^moodle/', include('moodle.urls', namespace="moodle")),
    url(r'^navbar/', include('navbar.urls', namespace="navbar")),
    url(r'^postjob/', include('postjob.urls', namespace="postjob")),
    url(r'^students/', include('students.urls', namespace="students")),
]

moodle/urls.py
from django.conf.urls import url
from . import views
from moodle import moodlepull
from django.contrib.auth import views as auth_views



urlpatterns = [
    url(r'^moodlemanager/$', views.moodlemanager, name="moodlemanager"),
    url(r'^dispatch/$', moodlepull.dispatch, name="dispatch"),
    url(r'^populategradetable/$', moodlepull.populategradetable, name="populategradetable"),
]

students/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views



urlpatterns = [
    url(r'^$', views.students, name="students"),
    url(r'^tokenreq/$', views.tokenreq, name="tokenreq"),
    url(r'^test/$', views.test, name="test"),
    url(r'^uni/$', views.uni, name="uni"),
    url(r'^getcoverletter/$', views.getcoverletter, name="getcoverletter"),
    url(r'^setcoverletter/$', views.setcoverletter, name="setcoverletter"),
    url(r'^summerimgupload/$', views.summerimgupload, name="summerimgupload"),
    url(r'^savedegree/$', views.savedegree, name="savedegree"),

]

students/models.py
from __future__ import unicode_literals
from django.db import models
from mongoengine import *
from mongoengine import connect
connect('eportdb')

# Create your models here.
class Studentdb(Document):
    userid = StringField()
    username = StringField()
    mysqlid = StringField()
    token = StringField()


class Vle(Document):
    name = StringField()
    version = StringField()
    url = StringField()
    service = StringField()
    other = StringField()

class Universitydb(Document):
    uniname = StringField()
    uniqid = StringField()
    unioutline = StringField()
    address = StringField()
    focus = ListField(ReferenceField(Studentdb))                    #focus
    vle = ReferenceField(Vle)
    icon = StringField()

class Coursedb(Document): #ref
    name = StringField()
    outline = StringField()
    focus = ListField(ReferenceField(Studentdb))                    #focus

class Modoutlinedb(Document): #ref
    modid  = StringField()
    shortname = StringField()
    fullname = StringField()
    modidtwo = StringField()
    summary = StringField()
    focus = ListField(ReferenceField(Studentdb))
    icon = StringField()                  #focus

class Coursepiecedb(EmbeddedDocument):
    header = StringField() #game design
    title = StringField()
    content = StringField()
    grade = StringField()
    feedback = StringField()
    graderange = StringField()
    position = IntField()
    piecetype = StringField()
    mediaurl = StringField()

class Skilldb(Document): #ref
    title = StringField()
    img = StringField()
    outline = StringField()

class Postdb(EmbeddedDocument):
    jobtitle = StringField()
    jobref = IntField()
    joboutline = StringField()
    datesent = DateTimeField()
    timeout = DateTimeField()

class Companydb(Document):
    company = StringField()
    banner = StringField()
    about = StringField()
    posts = ListField(EmbeddedDocumentListField(Postdb))
    focus =  ListField(ReferenceField(Studentdb))                   #focus

class Referencesdb(EmbeddedDocument):
    person = StringField()
    reference = StringField()
    email = StringField()
    company = ListField(ReferenceField(Companydb))

class Moduledb(Document):
    position = IntField()
    modulegrade = StringField()
    piece = ListField(EmbeddedDocumentListField(Coursepiecedb))
    references = ListField(EmbeddedDocumentField(Referencesdb))
    module = ReferenceField(Modoutlinedb)
    public = StringField()

class Workexpdb(EmbeddedDocument):
    position = IntField()
    company = ListField(EmbeddedDocumentField(Coursepiecedb))
    companytxt = StringField()
    companyabt = StringField()
    role = StringField()
    period = DateTimeField()
    references = ListField(EmbeddedDocumentField(Referencesdb))

class Usertimelinedb(Document):
    userid = StringField()
    user = ReferenceField(Studentdb)
    firstname = StringField()
    lastname = StringField()
    coverletter = StringField()
    university = ReferenceField(Universitydb)
    banner = StringField()
    age =  StringField()
    year =  StringField()
    email = StringField()
    coursestr = StringField()
    references = ListField(EmbeddedDocumentListField(Referencesdb))
    course = ListField(ReferenceField(Coursedb))
    modules = ListField(ReferenceField(Moduledb))
    skills = ListField(ReferenceField(Skilldb))
    workexp = ListField(EmbeddedDocumentListField(Workexpdb))
    newsfeed = ListField(EmbeddedDocumentListField(Postdb))



"""
Tags & Focuses

The main idea is that tags allow for the algorith to search for ideal candidates based on Tags
it should be able to create and delete tags and assign them to a user.

The idea of focuses is to know where to send of applications initially.
focuses are more to do with simple matchmaking rather than complex machine learning
they are always a good starting point

Module company university and course should each have their own ListField of studednts that have subscribed


Initial search == skills + focuses

solutin is to have a field that can store type company , uni , course and
"""

"""
class Focusesdb(Document):
    modfocuses = ListField(EmbeddedDocumentListField(Modoutlinedb))
    unifocus = ListField(EmbeddedDocumentField(Universitydb))
    coursefocus = ListField(EmbeddedDocumentListField(Moduledb))


    #req = ListField(EmbeddedDocumentField(Skilldb))"""

students/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.shortcuts import redirect
from django.core import serializers
from django import forms
from acounts.models import *
from students.models import *
import json
from bson import json_util
import urllib2
# Create your views here.
#import pdb; pdb.set_trace()


@login_required
def tokenreq(request):
    return HttpResponse("hello")

@login_required
def students(request):
    """
    if else statement to see if the student has loged in for the token
    """
    current_user = request.user
    user = AuthUser.objects.get(id=current_user.id)
    if (user.tokenised == 0):
        form = NameForm()
        return render(request, 'students/name.html', {'form': form})
    else:
        return render(request, 'students/eport.html', {'section': 'students'})


class NameForm(forms.Form):
    unis = Universitydb.objects()
    uni_list = []
    itt = 0
    for x in unis:
        uni_list.append( ("x.uniqid", "x.uniname") )
        itt += 1

    #your_uni = forms.ModelChoiceField(queryset=Universitydb.objects.all())

    #your_uni = forms.ModelChoiceField(queryset=Universitydb.objects.all().values_list('uniname'))
    #your_uni = forms.ChoiceField(choices=Universitydb.objects.values_list('uniname'), label="", initial='', widget=forms.Select(), required=True)
    #universities = forms.ChoiceField(choices=uni_list, required=True )
    your_name = forms.CharField(label='Username', max_length=100)
    your_pass = forms.CharField(widget=forms.PasswordInput, label='Password', max_length=100)

@login_required
def uni(request):
    term = request.GET.get('query', '')
    posterms = Universitydb.objects.filter(uniname__contains = term)

    unilist = []
    for uni in posterms:
        ut = { "value": uni.uniname, "data": uni.uniqid}
        unilist.append(ut)

    #posterms = Universitydb.objects.filter(tags__in = term)
    #city_array = ["greece","germany","gambone","grenoa"]
    #json_cities = json.dumps(city_array)
    city = {"query": "Unit","suggestions": unilist  }
    return JsonResponse(city)

"""
class CountryAutocomplete(autocomplete.Select2QuerySetView):
    def get_queryset(self):
        # Don't forget to filter out results depending on the visitor !
        if not self.request.user.is_authenticated():
            return Country.objects.none()

        qs = Country.objects.all()

        if self.q:
            qs = qs.filter(name__istartswith=self.q)

        return qs
"""

@login_required
def test(request):
    #term = request.GET.get('query', '')
    term = 'Univ'
    posterms = Universitydb.objects.filter(uniname__contains = term)
    #unilist = []
    #for pos in posterms:
        #unilist.append(pos.uniname)

    return HttpResponse(posterms[0].uniname)


@login_required
def router(request):
    return HttpResponse("determine which uni/VLE the student is at using")


def dispatcher(request):
    return HttpResponse("Dispatch student data to the correct app to fire off events")

@login_required
def getcoverletter(request):
    userid = request.user.id
    student  = Studentdb.objects.get(mysqlid = userid.__str__())
    ut = Usertimelinedb.objects.get(user = student)
    coverletter = ut.coverletter
    return HttpResponse(coverletter)

@login_required
def setcoverletter(request):
    coverletter = request.GET['x']
    userid = request.user.id
    student  = Studentdb.objects.get(mysqlid = userid.__str__())
    ut = Usertimelinedb.objects.get(user = student)
    ut.coverletter = coverletter
    ut.save()
    return HttpResponse("sucess")

@login_required
def savedegree(request):
    degree = request.POST['degree']
    userid = request.user.id
    student  = Studentdb.objects.get(mysqlid = userid.__str__())
    ut = Usertimelinedb.objects.get(user = student)
    ut.coursestr = degree
    ut.save()
    return HttpResponse("sucess")

@login_required
def loadmodule(request):
    return render(request, 'students/module.html', {'section': 'module'})

@login_required
def summerimgupload(request):
    return HttpResponse("http://res.cloudinary.com/dhasw4cz8/image/upload/v1490558303/tuning-2157354_640_lzgjwa.jpg")
    """
    Sample db entries
    posterms = Universitydb.objects.filter(uniname__contains = term)
    posterms[0].uniname
    """

students/templates/students/eport.html
{% extends "navbar/base.html" %}
{% block title %}editor{% endblock %}


{% block content %}
{% load static %}
<link rel="stylesheet" type="text/css" href=" {% static "students/css/students.css" %}"/>
<link rel="stylesheet" type="text/css" href=" {% static "students/css/timeline.css" %}"/>
<script src=" {% static "students/js/jquery-3.2.1.min.js" %}"></script>
<script src=" {% static "students/js/readmore.js" %}"></script>
<script src=" {% static "students/js/js.cookie.js" %}"></script>
<link href="http://netdna.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.css" rel="stylesheet">
 <script src="http://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.js"></script>
 <script src="http://netdna.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.js"></script>
 <link href="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.6/summernote.css" rel="stylesheet">
 <script src="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.6/summernote.js"></script>
<link rel="stylesheet" href="https://cdn.rawgit.com/konpa/devicon/df6431e323547add1b4cf45992913f15286456d3/devicon.min.css">

{% load timelinetags %}
  <div id="timeline-wrapper">
    <div id="header-wrapper">
      <div id="logo-header"><img id="logo-uni" src="{% img_tag request.user.id %}"></img></div>
      <div id="Name"> {% name_tag request.user.id %}</div>
      <div id="University">{% uni_tag request.user.id %}</div>
      <div id="Degree">

        {% get_degree request.user.id as degree %}
        {% if degree == None %}
          <input id="degree-input" class="hideit" placeholder="Enter Degree"></input>
        {% else %}
          <label id="degree-label" placeholder="">{{ degree }}</input>
          <div class="grad-edit"></div>
        {% endif %}
      </div>
    </div>

    {% csrf_token %}
    <div id="coverletter">
      <div id="summernote"></div>
      <div id="modify-highlighter"></div>
      <div id="modify-button" class="summer-active"></div>
    </div>
    <div id="add-piece-btn"></div>

    <div id="pieces-wrapper">

        {% get_mods request.user.id as mods %}
        {% for o in mods %}
          <div id="{% get_mongo_id o %}" class="piece">
            <div class="piece-logo"><img id="piece-img"></img></div>
            <div class="modulename"><div class='label-modname'>{{ o.module.fullname }}</div></div>
            <article class="module-summary slide" id="module-summary">{% autoescape off %}{{ o.module.summary }}{% endautoescape %}</article>
            <div class="mod-mark">{{ o.modulegrade }}</div>
            <div class="actions-container">
              <img id="top-arrow" src="http://res.cloudinary.com/dhasw4cz8/image/upload/v1502546294/gradport/Keyboard_Arrow_Up.png" id="1" class="actions-control"></img>
              <img src="http://res.cloudinary.com/dhasw4cz8/image/upload/v1502546292/gradport/Keyboard_Arrow_Down.png" id="3" class="actions-control"></img>
            </div>
            <div id="delete-piece"></div>
          </div>
        {% endfor %}

    </div>
  </div>


    <!-- in your header -->
  <link rel="stylesheet" href="https://cdn.rawgit.com/konpa/devicon/df6431e323547add1b4cf45992913f15286456d3/devicon.min.css">



  <div id="skills-wrapper">Skills

    <!-- in your body -->
    <i class="devicon-android-plain colored"></i>

    <i class="devicon-java-plain-wordmark colored"></i>

     <i class="devicon-visualstudio-plain colored"></i>
    <div id="add-skill"></div>

  </div>

  <script>


    $(document).ready(function(){
          //security
          var csrftoken = Cookies.get('csrftoken');
          function csrfSafeMethod(method) {
          // these HTTP methods do not require CSRF protection
            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
          }
          $.ajaxSetup({
          beforeSend: function(xhr, settings) {
              if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                  xhr.setRequestHeader("X-CSRFToken", csrftoken);
              }
            }
          });




       function editit(){
             var text = $(this).val();
             var degree = $("<input id='degree-input' class='hideit' placeholder='Enter Degree'></input>").blur(blurit);
             $('#Degree').html(degree);
          }


      function blurit(){
              alert("sadas");
              var text = $(this).val();
              $.ajax({
                type: 'POST',
                data: {
                  degree: text,
                },
                url: "{% url 'students:savedegree' %}",
                datatype: "json",
                     success: function(data) {
                       var label = $("<label id='degree-label' placeholder=''>"+ text +"</input>");
                       var edit = $("<div class='grad-edit'></div>").click(editit);
                       $("#Degree").html(label);
                       $("#Degree").append(edit);
                     }
                 });
            }



            $('.grad-edit').on('click', function(){
                  var degree = $("<input id='degree-input' class='hideit' placeholder='Enter Degree'></input>").blur(blurit);
                  $('#Degree').html(degree);
             });


          $('#degree-input').blur(function(){
            var text = $(this).val();
            $.ajax({
              type: 'POST',
              data: {
                degree: text,
              },
              url: "{% url 'students:savedegree' %}",
              datatype: "json",
                   success: function(data) {
                     var label = $("<label id='degree-label' placeholder=''>"+ text +"</input>");
                     var edit = $("<div class='grad-edit'></div>").click(editit);
                     $("#Degree").html(label);
                     $("#Degree").append(edit);
                   }
               });
          });


        var markupStr = "Type up your cover-letter here";
        //ajax to get coverletter data
        var getcoverletter = function getcoverletter(callback){
          $.ajax({
            type: 'GET',
            url: "{% url 'students:getcoverletter' %}",
            datatype: "json",
                 success: function(data) {
                   callback(data);
                 }
             });
        }
       function starteditor(data){
         markupStr = data;
         $('#summernote').summernote('code', markupStr);
      }
      getcoverletter(starteditor);


      var SaveButton = function (context) {
      var ui = $.summernote.ui;

      // create button
      var button = ui.button({
        contents: '<i class="fa fa-child"/> Save',
        tooltip: 'Save',
        click: function () {
          $('#summernote').summernote('destroy');
          $('.tooltip').css({'visibility':'hidden'});
          $( '#modify-button' ).show();
          $('#modify-highlighter').show();
          //context.invoke('editor.insertText', 'hello');
        }
      });

      return button.render();   // return button as jquery object
      }


      $('#summernote').summernote({
          toolbar: [
            ['mybutton', ['Save']],
            ['style', ['bold', 'italic', 'underline', 'clear']],
            ['fontsize', ['fontsize']],
            ['color', ['color']],
            ['para', ['ul', 'ol', 'paragraph']],
            ['height', ['height']],
            ['insert',['picture','link','video']]
          ],
          buttons: {
            Save: SaveButton
          },
          callbacks: {
            onImageUpload: function(files, editor, welEditable) {
              url  = sendFile(files[0], this);
              $('#summernote').summernote('insertImage', url);
              // upload image to server and create imgNode...
            },
            onChange: function(x) {
              //console.log('onChange:', contents, $editable);
              $.ajax({
                type: "GET",
                url: "{% url 'students:setcoverletter' %}",
                data: {
                      x: x ,
                    },
                datatype: "json",
                     success: function(data) {
                     }
                 });
                console.log("something happened");
            }

          }
      });

      function sendFile(file, el) {
        jQuery.noConflict();
        data = new FormData();
        data.append("file", file);
        $.ajax({
          type: "GET",
          url: "{% url 'students:summerimgupload' %}",
          data: data,
          processData: false,
          contentType: false,
          datatype: "json",
               success: function(data) {
                 var url = "http://res.cloudinary.com/dhasw4cz8/image/upload/v1490558303/tuning-2157354_640_lzgjwa.jpg";
                 //$('#summernote').summernote('insertImage', url);
                 return(url);
               }
           });
      }


      $("#modify-button").on('click' ,function(){
          getcoverletter(starteditor);
          $("#modify-button").hide();
          $("#modify-highlighter").hide();


          $('#summernote').summernote({
              toolbar: [
                ['mybutton', ['Save']],
                ['style', ['bold', 'italic', 'underline', 'clear']],
                ['fontsize', ['fontsize']],
                ['color', ['color']],
                ['para', ['ul', 'ol', 'paragraph']],
                ['height', ['height']],
                ['insert',['picture','link','video']]
              ],
              buttons: {
                Save: SaveButton
              },
              callbacks: {
                onImageUpload: function(files, editor, welEditable) {
                  url  = sendFile(files[0], this);
                  $('#summernote').summernote('insertImage', url);
                  // upload image to server and create imgNode...
                },
                onChange: function(x) {
                  //console.log('onChange:', contents, $editable);
                  $.ajax({
                    type: "GET",
                    url: "{% url 'students:setcoverletter' %}",
                    data: {
                          x: x ,
                        },
                    datatype: "json",
                         success: function(data) {
                         }
                     });
                    console.log("something happened");
                }

              }
          });
      });

        $("#TestBtn1").on('click', function(){
            var markupStr = $('#summernote').summernote('code');
        });


        $(".piece").on('click', function(){
          var finalvar = "";
          alert($(this).attr('id'));
          $.ajax({
            type: "GET",
            url: "{% url 'moodle:dispatch' %}",
            data: {
                  objectid: $(this).attr('id'),
                },
            datatype: "json",
                 success: function(data) {
                    finalvar = data;
                 }
             });


            $(this).fadeOut("slow", function(){
                var childdiv = $(finalvar);
                var div = $("<div class='module-wrapper'><div class='module-head'><div class='mod-back'></div></div><div class='module-body'>body</div></div>").hide();
                div.append(childdiv);
                $(this).replaceWith(div);
                $(div).fadeIn("slow");

            });
        });


    });

  </script>

{% endblock %}

students/templates/students/name.html
{% extends "navbar/base.html" %}
{% block title %}name{% endblock %}


{% block content %}
{% load static %}
<link rel="stylesheet" type="text/css" href=" {% static "students/css/students.css" %}"/>
<script src=" {% static "students/js/jquery-3.2.1.min.js" %}"></script>
<script src=" {% static "students/js/js.cookie.js" %}"></script>

<link rel="stylesheet" type="text/css" href=" {% static "students/css/jquery.auto-complete.css" %}"/>
<script src=" {% static "students/js/jquery.autocomplete.js" %}"></script>

<div id="plug">
  <form id="post-form" class="post-form" >
    <p>Please enter your university credentials</p>
    <input type="text" name="country" id="autocomplete"/>
    {% csrf_token %}
    {{ form }}
    <div id="Submit">Submit</div>
</form>

</div>

<script>


$(document).ready(function(){

    var uniselectionid = 0;
    /// Django csrf logic
    /// get and seet token to ajax header
    var csrftoken = Cookies.get('csrftoken');
    function csrfSafeMethod(method) {
    // these HTTP methods do not require CSRF protection
      return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }
    $.ajaxSetup({
    beforeSend: function(xhr, settings) {
        if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
            xhr.setRequestHeader("X-CSRFToken", csrftoken);
        }
      }
    });

    ////////////////////////////////////////////////////

    /*
    $('input[name="q"]').autoComplete({
        source: function(term, response){
            $.getJSON("{% url 'students:uni' %}", { q: term }, function(data){ response(data); });
        }
    });
    */

    /*
    $("#unidrop").on('change', function(){
      $.ajax({
        type: 'GET',
        url: "{% url 'students:uni' %}",
        datatype: "json",
             success: function(data) {
                 $("#unidrop").autocomplete({ source: data });
             }
         });
    });*/

    /*
    $('#unidrop').autoComplete({
      source: function(term, response){
          $.ajax({
          type: 'GET',
          url: "{% url 'students:uni' %}",
          datatype: "json",
               success: function(data) {
                 response(data);
               }
           });
      }
    }); */
    $('#autocomplete').autocomplete({
      serviceUrl: "{% url 'students:uni' %}",
      onSelect: function (suggestion) {
          uniselectionid = suggestion.data
          console.log(uniselectionid);
        }
      });



    $("#TestBtn1").on('click', function(){
      $.ajax({
        type: 'GET',
        url: "{% url 'students:test' %}",
        datatype: "json",
             success: function(data) {
              alert(data);
             }
         });
    });

    /*
    $.ajaxSetup({data: {
      csrfmiddlewaretoken: '{{ csrf_token }}'
    }}); */

    $("#Submit").on('click',function(){
      var user = document.getElementById("id_your_name").value;
      var pass = document.getElementById("id_your_pass").value;
      var uniqid = uniselectionid;
      if(user == "" || pass == ""){
        //do nothing
      }
      else{
          $.ajax({
            type: 'GET',
            data: {
                  username: user ,
                  password: pass,
                  uniqid: uniselectionid
                },
            url: "{% url 'moodle:moodlemanager' %}",
            datatype: "json",
                 success: function(data) {
                   window.location.href = "{% url 'students:students' %}";
                 }
             });
          }

       });
    });

//http://127.0.1.1/moodle/webservice/rest/server.php?wstoken=6b1e98bff72b9c93eab1387c217e95fd&wsfunction=gradereport_user_get_grade_items&moodlewsrestformat=json
</script>

{% endblock %}