eport/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf.urls import include, url

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('gateway.urls', namespace="gateway") ),
    url(r'^acounts/', include('acounts.urls', namespace="acounts")),
    url(r'^applyjob/', include('applyjob.urls', namespace="applyjob")),
    url(r'^companies/', include('companies.urls', namespace="companies")),
    url(r'^moodle/', include('moodle.urls', namespace="moodle")),
    url(r'^navbar/', include('navbar.urls', namespace="navbar")),
    url(r'^postjob/', include('postjob.urls', namespace="postjob")),
    url(r'^students/', include('students.urls', namespace="students")),
]

gateway/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views



urlpatterns = [
    url(r'^$', views.gateway, name="gateway"),
    url(r'^eport/$', views.eport, name="eport"),
    url(r'^studentreg/$', views.studentreg, name="studentreg"),
]

gateway/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

gateway/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.shortcuts import redirect
from django.core import serializers
# Create your views here.
from students import views as st


# -----   Determin if company or student ---- redirect to those apps
# --- import student
# --- import companies


@login_required
def eport(request):
    data = st.students(request)
    return HttpResponse(data)
    #return render(request, 'gateway/userportal.html', {'section': 'eport'})


def gateway(request):
    return render(request, 'gateway/userportal.html')


def studentreg(request):
    return HttpResponse("it worked")

gateway/templates/gateway/userportal.html
<!DOCTYPE html>
<html>
<head>
<title>Gradport</title>
{% load static %}
<link rel="stylesheet" type="text/css" href=" {% static "gateway/css/userportal.css" %}"/>
<script src=" {% static "gateway/js/jquery-2.2.0.js" %}"></script>

</head>
<body>
<!-- Start your code here -->
<div id="background">
  <h1 id="title">Gradport</h1>
  <div id="container">
    <div class="student">Student Registration</div>

    <div class="company">Company Registration</div>
  </div>
</div>

<a id="login" href="{% url 'gateway:eport' %}">login</a>
<script>
$(document).ready(function(){

  $(".student").on('click', function(){
    $.ajax({
          type: "GET",
          url: "studentreg/",
           success: function(data) {
             alert(data);
           }
       })
     });

  $(".company").on('click', function(){
    alert("2");
  });



});



</script>
<!-- End your code here -->
</body>
</html>