acounts/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
	url(r'^login/$', auth_views.login, name="login"),
	url(r'^logout/$', auth_views.logout, name="logout"),
	url(r'^logout-then-login/$', auth_views.logout_then_login, name='logout_then_login'),
]

eport/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf.urls import include, url

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('gateway.urls', namespace="gateway") ),
    url(r'^acounts/', include('acounts.urls', namespace="acounts")),
    url(r'^applyjob/', include('applyjob.urls', namespace="applyjob")),
    url(r'^companies/', include('companies.urls', namespace="companies")),
    url(r'^moodle/', include('moodle.urls', namespace="moodle")),
    url(r'^navbar/', include('navbar.urls', namespace="navbar")),
    url(r'^postjob/', include('postjob.urls', namespace="postjob")),
    url(r'^students/', include('students.urls', namespace="students")),
]

gateway/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views



urlpatterns = [
    url(r'^$', views.gateway, name="gateway"),
    url(r'^eport/$', views.eport, name="eport"),
    url(r'^studentreg/$', views.studentreg, name="studentreg"),
]

navbar/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views



urlpatterns = [
    url(r'^$', views.navbar, name="navbar"),
]

navbar/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

navbar/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.shortcuts import redirect
from django.core import serializers

# Create your views here.
@login_required
def navbar(request):
    return render(request, 'navbar/base.html')

navbar/templates/navbar/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Eport</title>

    {% load static %}
    <link rel="stylesheet" type="text/css" href=" {% static "navbar/css/main.css" %}"/>

</head>
<body>
  <div id="homelogo"></div>



  <div id="full-view">
      <div id="header">

        {% if request.user.is_authenticated %}
        <div class="menu">
          <ul>
            <li {% if section == "eport" %}class="selected"{% endif %}>
               <a href="{% url "gateway:gateway" %}">eport</a>
            </li>
        </ul>
      </div>
        {% endif %}

           <div class="user">
             <a href="{% url "acounts:logout" %}">Eport</a>
            {% if request.user.is_authenticated %}
              Hello {{ request.user.username }},
              <a href="{% url "acounts:logout" %}?next=/eport">Logout</a>
              {% else %}
              <a href="{% url "acounts:login" %}">Log-in</a>
            {% endif %}
          </div>


      </div>
      <div id="cell1"></div>
     </div>

     <div id="TestBtn1">Test!</div>
     {% block content %}
     {% endblock %}


</body>
</html>